//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Caso1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t002_colonias
    {
        public int id_colonia { get; set; }
        public string nom_colonia { get; set; }
    }
}
